version: '3.3'

services:
  web_fe:
    build: .
    command: >
      sh -c "
        nginx -g 'daemon off;'"
    expose:
        - 80
    volumes:
        - ./app:/usr/share/nginx/html
    ports:
      - "8081:80"
